### PR TITLE
Linux, MacOS X and Windows releases

### PR DESCRIPTION
**Pull request by cameel**
Depends on on #40. Part of https://github.com/ethereum/solidity/issues/9258.

Release binaries downloaded using the script from #41.

### CODE REVIEW

**Comment by cameel** [comment]
Here's the one-off script I used to get them. The script must be in the same directory as `download-release.sh` from #41.
Since it's pretty easy to run into the API rate limit, the script keeps track of already downloaded versions and can resume from where it got interrupted.

``` bash
#!/usr/bin/env bash

set -e

script_dir="$(dirname "$0")"

echo "===> FETCHING RELEASE LIST"
available_versions="$(
    curl --fail --silent --show-error "https://api.github.com/repos/ethereum/solidity/releases?per_page=100" |
    jq --raw-output '.[].tag_name' |
    sort
)"

touch downloaded-versions.txt
downloaded_versions="$(cat downloaded-versions.txt | sort)"
remaining_versions="$(comm -23 <(echo "$available_versions") <(echo "$downloaded_versions"))"

printf "Already downloaded:\n%s\n" "$downloaded_versions"
printf "Remaining:\n%s\n" "$remaining_versions"

for version in $remaining_versions; do
    "${script_dir}/download-release.sh" github "$version"
    echo "$version" >> downloaded-versions.txt
done
```

I'm also attaching the log from my run of the script in case you want to take a look at which artifacts and versions were available and which ones the script selected: [release-download-log-2020-07-16.txt](https://github.com/ethereum/solc-bin/files/4935156/release-download-log-2020-07-16.txt).

**Comment by cameel** [comment]
And here is a listing of binaries available on the release page and in `solc-bin`.

Notation:
- **C** means that that the binary was built from the same commit but file content differs.
- **V** means that that the binary was built from a different commit than the github release.

| ver      | linux    | macos    | windows  | asm.js (GH release) | asm.js (`bin/`) | wasm32 (GH release) | wasm32 (`wasm/`) |
|----------|----------|----------|----------|-------------|-----------------|-------------|------------------|
| 0.1.0    |          |          |          |             |                 |             |                  |
| 0.1.1    |          |          |          |             | 6ff4cd6         |             |                  |
| 0.1.2    |          |          |          |             | d0d36e3         |             |                  |
| 0.1.3    |          |          |          | 028f561d    | 028f561d        |             |                  |
| 0.1.4    |          |          |          |             | 5f6c3cdf        |             |                  |
| 0.1.5    |          |          |          |             | 23865e39        |             |                  |
| 0.1.6    |          |          |          |             | d41f8b7c        |             |                  |
| 0.1.7    |          |          |          |             | b4e666cc        |             |                  |
| 0.2.0    |          |          |          | 4dc2445e    | 4dc2445e **C**  |             |                  |
| 0.2.1    |          |          |          | 91a6b35f    | 91a6b35f **C**  |             |                  |
| 0.2.2    |          |          |          |             | ef92f566        |             |                  |
| 0.3.0    |          |          |          |             | 11d67369        |             |                  |
| 0.3.1    |          |          |          |             | c492d9be        |             |                  |
| 0.3.2    |          |          |          |             | 81ae2a78        |             |                  |
| 0.3.3    |          |          |          |             | 4dc1cb14        |             |                  |
| 0.3.4    |          |          |          |             | 7dab8902        |             |                  |
| 0.3.5    |          |          |          |             | 5f97274a        |             |                  |
| 0.3.6    |          |          |          |             | 3fc68da5        |             | 3fc68da5         |
| 0.4.0    |          |          |          | acd334c9    | acd334c9        |             | acd334c9         |
| 0.4.1    | 4fc6fc2c |          | 4fc6fc2c | 4fc6fc2c    | 4fc6fc2c        |             | 4fc6fc2c         |
| 0.4.2    | af6afb04 |          | af6afb04 |             | af6afb04        |             | af6afb04         |
| 0.4.3    |          |          |          | 2353da71    | 2353da71        |             | 2353da71         |
| 0.4.4    |          |          |          |             | 4633f3de        |             | 4633f3de         |
| 0.4.5    |          |          | b318366e | b318366e    | b318366e        |             | b318366e         |
| 0.4.6    |          |          | 2dabbdf0 |             | 2dabbdf0        |             | 2dabbdf0         |
| 0.4.7    |          |          | 822622cf | 822622cf    | 822622cf        |             | 822622cf         |
| 0.4.8    |          |          | 60cc1668 | 60cc1668    | 60cc1668        |             | 60cc1668         |
| 0.4.9    |          |          | 364da425 |             | 364da425        |             | 364da425         |
| 0.4.10   | f0d539ae |          | f0d539ae |             | f0d539ae        |             | f0d539ae         |
| 0.4.11   | 68ef5810 |          | 68ef5810 | 68ef5810    | 68ef5810 **C**  |             | 68ef5810         |
| 0.4.12   | 194ff033 |          | 194ff033 | 194ff033    | 194ff033        |             | 194ff033         |
| 0.4.13   | 0fb4cb1a |          | 0fb4cb1a | 0fb4cb1a    | 0fb4cb1a        |             | 0fb4cb1a         |
| 0.4.14   | c2215d46 |          | c2215d46 | c2215d46    | c2215d46        |             | c2215d46         |
| 0.4.15   | 8b45bddb |          | 8b45bddb | 8b45bddb    | bbb8e64f **V**  |             | bbb8e64f **V**   |
| 0.4.16   | d7661dd9 |          | d7661dd9 | d7661dd9    | d7661dd9        |             | d7661dd9         |
| 0.4.17   | bdeb9e52 |          | bdeb9e52 | bdeb9e52    | bdeb9e52        |             | bdeb9e52         |
| 0.4.18   | 9cf6e910 |          | 9cf6e910 | 9cf6e910    | 9cf6e910        |             | 9cf6e910         |
| 0.4.19   | c4cbbb05 |          | c4cbbb05 | c4cbbb05    | c4cbbb05        |             | c4cbbb05         |
| 0.4.20   | 3155dd80 |          | 3155dd80 | 3155dd80    | 3155dd80        |             | 3155dd80         |
| 0.4.21   | dfe3193c |          | dfe3193c | dfe3193c    | dfe3193c        |             | dfe3193c         |
| 0.4.22   | 4cb486ee |          | 4cb486ee | 4cb486ee    | 4cb486ee        |             | 4cb486ee         |
| 0.4.23   | 124ca40d |          | 124ca40d | 124ca40d    | 124ca40d        |             | 124ca40d         |
| 0.4.24   | e67f0147 |          | e67f0147 | e67f0147    | e67f0147        |             | e67f0147         |
| 0.4.25   | 59dbf8f1 |          | 59dbf8f1 | 59dbf8f1    | 59dbf8f1        |             | 59dbf8f1         |
| 0.4.26   | 4563c3fc |          | 4563c3fc | 4563c3fc    | 4563c3fc        |             | 4563c3fc         |
| 0.5.0    | 1d4f565a |          | 1d4f565a | 1d4f565a    | 1d4f565a        |             | 1d4f565a         |
| 0.5.1    | c8a2cb62 |          | c8a2cb62 | c8a2cb62    | c8a2cb62        |             | c8a2cb62         |
| 0.5.2    | 1df8f40c |          | 1df8f40c | 1df8f40c    | 1df8f40c        |             | 1df8f40c         |
| 0.5.3    | 10d17f24 |          | 10d17f24 | 10d17f24    | 10d17f24        |             | 10d17f24         |
| 0.5.4    | 9549d8ff |          | 9549d8ff | 9549d8ff    | 9549d8ff        |             | 9549d8ff         |
| 0.5.5    | 47a71e8f |          | 47a71e8f | 47a71e8f    | 47a71e8f        |             | 47a71e8f         |
| 0.5.6    | b259423e |          | b259423e | b259423e    | b259423e        |             | b259423e         |
| 0.5.7    | 6da8b019 |          | 6da8b019 | 6da8b019    | 6da8b019        |             | 6da8b019         |
| 0.5.8    | 23d335f2 |          | 23d335f2 | 23d335f2    | 23d335f2        |             | 23d335f2         |
| 0.5.9    | c68bc34e |          | c68bc34e | c68bc34e    | e560f70d **V**  |             | e560f70d **V**   |
| 0.5.10   | 5a6ea5b1 |          | 5a6ea5b1 | 5a6ea5b1    | 5a6ea5b1        |             | 5a6ea5b1         |
| 0.5.11   | 22be8592 |          | 22be8592 | 22be8592    | c082d0b4 **V**  |             | c082d0b4 **V**   |
| 0.5.12   | 7709ece9 |          | 7709ece9 | 7709ece9    | 7709ece9        |             | 7709ece9         |
| 0.5.13   | 5b0b510c |          | 5b0b510c | 5b0b510c    | 5b0b510c        |             | 5b0b510c         |
| 0.5.14   | 01f1aaa4 |          | 01f1aaa4 | 01f1aaa4    | 01f1aaa4        |             | 01f1aaa4         |
| 0.5.15   | 6a57276f |          | 6a57276f | 6a57276f    | 6a57276f        |             | 6a57276f         |
| 0.5.16   | 9c3226ce |          | 9c3226ce | 9c3226ce    | 9c3226ce        |             | 9c3226ce         |
| 0.5.17   | d19bba13 |          | d19bba13 | d19bba13    | d19bba13        |             |                  |
| 0.6.0    | 26b70077 |          | 26b70077 | 26b70077    | 26b70077        |             | 26b70077         |
| 0.6.1    | e6f7d5a4 |          | e6f7d5a4 | e6f7d5a4    | e6f7d5a4        |             | e6f7d5a4         |
| 0.6.2    | bacdbe57 |          | bacdbe57 |             |                 | bacdbe57    | bacdbe57         |
| 0.6.3    | 8dda9521 |          | 8dda9521 |             |                 | 8dda9521    | 8dda9521         |
| 0.6.4    | 1dca32f3 |          | 1dca32f3 |             |                 | 1dca32f3    | 1dca32f3         |
| 0.6.5    | f956cc89 |          | f956cc89 |             |                 | f956cc89    | f956cc89         |
| 0.6.6    | 6c089d02 |          | 6c089d02 |             |                 | 6c089d02    | 6c089d02         |
| 0.6.7    | b8d736ae |          | b8d736ae |             |                 | b8d736ae    | b8d736ae         |
| 0.6.8    | 0bbfe453 |          | 0bbfe453 |             |                 | 0bbfe453    | 0bbfe453         |
| 0.6.9    | 3e3065ac | 3e3065ac | 3e3065ac |             |                 | 3e3065ac    | 3e3065ac         |
| 0.6.10   | 00c0fcaf | 00c0fcaf | 00c0fcaf |             |                 | 00c0fcaf    | 00c0fcaf         |
| 0.6.11   | 5ef660b1 | 5ef660b1 | 5ef660b1 |             |                 | 5ef660b1    | 5ef660b1         |

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
It would be great to get macos builds for older versions, but I think this can be done separately.

**Comment by cameel** [comment]
@chriseth Could you create an issue for that? I think it needs some details on how we want to get them (one-off job on gh-actions or Circle CI? or maybe just build them locally and upload?). Do we want to put them on release pages as well?

**Comment by chriseth** [comment]
We can use that issue for it: https://github.com/ethereum/solidity/issues/9226

I think the binaries have to be built locally, but I don't think we have to put them on the release pages.

**Pull request merged**
