### PR TITLE
Add missing wasm symlinks to release 0.6.12

### PR DESCRIPTION
**Pull request by cameel**
Fixes #45.

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
travis job failed because of missing newline...

**Comment by cameel** [comment]
What? In a symlink? WTF.

**Comment by cameel** [comment]
Wait, it's probably just that the diff after `update` is not clean. I'll rerun it locally and see what might be the cause.

**Comment by cameel** [comment]
Looks like the `update` script did not update the `latest` symlink in `wasm/` on my machine. Not sure why - I ran the clean version from `gh-pages` which should have done it. Anyway, rerunning locally to fix it.

**Comment by cameel** [comment]
Fixed.

I think I know what's going on. It did not wait for `wasm/` to be processed (which includes creating symlinks to the new release in `emscripten-wasm32/`) before it started processing `emscripten-wasm32/`. It did not see the new symlink and therefore did not update the lists. That's despite doing the second update in a callback which I added specifically to prevent this.

This is the same issue I've just been fighting with after modifying the `update` script. This means that my changes are fine and the issue is actually already there, just not always reproducible.  I'll debug it tomorrow - for now, just rerunning it should be enough to fix this PR.

**Review by chriseth — APPROVED** [review]

**Comment by cameel** [comment]
I just pushed #49 which automates creation of these symlinks.

**Pull request merged**
