### PR TITLE
Add webassembly rebuilds.

### PR DESCRIPTION
**Pull request by ekpyron**
For reviewing the changes to the update script I suggest not displaying whiteplace changes.

This depends on us changing the release scripts in the solidity repo to keep generate symlinks for new releases from ``bin`` to ``wasm`` (or the other way around).

### CODE REVIEW

**Comment by ekpyron** [comment]
There also needs to be a decision about the leading zero for 0.4.13 and 0.5.14.
The ``wasm`` directory here has them, but so far ``bin`` doesn't.

**Comment by ekpyron** [comment]
I'm changing the order of same-day nightlies in ``bin/list*`` as well... the tests seem to be broken for ``gh-pages`` itself in that regard apparently...

**Comment by ekpyron** [comment]
Honestly I don't know how semver does its sorting for the commit hashes...

**Comment by ekpyron** [comment]
Ah, wait, I need to add 0.6.2 to the ``wasm`` folder as well now. Updating...

**Comment by ekpyron** [comment]
Updated again now including 0.6.2 in the wasm folder.

**Comment by ekpyron** [comment]
Should I change the upload script in the solidity repo to add links to the wasm directory for releases?

**Comment by chriseth** [comment]
Yes, please!

**Comment by ekpyron** [comment]
See https://github.com/ethereum/solidity/pull/8227

**Pull request merged**
